"""Cross-epsilon aggregation for the anisotropic experiment, and the LaTeX.

    python -m hcsm.collect_tensor --results results/tensor --out results/tensor

Writes ``summary.csv`` (tidy long form), ``analysis.tex`` (the LaTeX analysis,
with every number read back from the per-run ``metrics.json`` so nothing is
transcribed by hand) and the console comparison tables.

The LaTeX keeps the four claims the specification insists on separating:

  * demonstrated weaknesses of particular classical smoothers,
  * improvement on the difficult modes,
  * performance on the broader error families,
  * actual multigrid solver performance.

They are four different statements and a table that mixes them is not evidence
for any of them.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import sys
from typing import Dict, List, Optional, Sequence

import numpy as np

from .aniso_errors import FAMILIES
from .problem import TENSOR_EPSILONS, eps_tag

METHODS = ("jacobi", "gs", "sgs_ssor")
LEARNED = "deeponet_scale"
#: Sweep counts behind each classical method, recorded so "one step" is never
#: ambiguous: symmetric Gauss-Seidel is a forward AND a backward sweep.
SWEEPS = {"jacobi": "1 (damped, omega from validation)",
          "gs": "1 forward sweep",
          "sgs_ssor": "1 symmetric application = forward + backward sweep"}


def load(results_dir: str) -> Dict[str, Dict[str, object]]:
    out = {}
    for p in sorted(glob.glob(os.path.join(results_dir, "eps-*", "metrics.json"))):
        with open(p) as fh:
            m = json.load(fh)
        out[m["tag"]] = m
    if not out:
        raise SystemExit("no metrics.json under %s/eps-*/" % results_dir)
    return out


def tag_order(metrics) -> List[str]:
    return sorted(metrics.keys(), key=lambda t: -float(t))


def eps_label(tag: str) -> str:
    return r"$10^{%d}$" % int(round(np.log10(float(tag)))) \
        if abs(float(tag) - 1.0) > 1e-12 else r"$1$"


def _cell(block, fam, meth, which, stat):
    try:
        return block[fam][meth][which][stat]
    except (KeyError, TypeError):
        return float("nan")


def write_summary_csv(metrics: Dict[str, Dict[str, object]], path: str) -> int:
    rows = 0
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["epsilon", "anisotropy", "block", "family", "method",
                    "ratio_kind", "statistic", "value"])
        for tag, m in metrics.items():
            for block_name in ("classical_families", "deeponet_families",
                               "classical_stress", "deeponet_stress"):
                block = m.get(block_name) or {}
                for fam, meths in block.items():
                    for meth, d in meths.items():
                        for which in ("full", "complement"):
                            for stat, val in d[which].items():
                                w.writerow([m["epsilon"], m["anisotropy"],
                                            block_name, fam, meth, which, stat,
                                            val])
                                rows += 1
            for name, vc in (m.get("vcycle") or {}).items():
                if not isinstance(vc, dict) or "mean_rate" not in vc:
                    continue
                for stat in ("mean_rate", "worst_rate", "mean_iterations",
                             "seconds_per_rhs"):
                    w.writerow([m["epsilon"], m["anisotropy"], "vcycle", "-",
                                name, "stationary", stat, vc[stat]])
                    rows += 1
    return rows


# ---------------------------------------------------------------------------
# LaTeX
# ---------------------------------------------------------------------------


def _tex_table(metrics, tags, blocks, method, which, stat, caption, label) -> str:
    head = " & ".join(eps_label(t) for t in tags)
    lines = [
        r"\begin{table}[htbp]\centering",
        r"\caption{%s}" % caption,
        r"\label{%s}" % label,
        r"\begin{tabular}{l%s}" % ("r" * len(tags)),
        r"\toprule",
        r"error family & " + head + r" \\",
        r"\midrule",
    ]
    for fam in FAMILIES:
        cells = []
        for t in tags:
            block = metrics[t].get(blocks) or {}
            v = _cell(block, fam, method, which, stat)
            cells.append("--" if not np.isfinite(v) else "%.3f" % v)
        lines.append(r"%s & %s \\" % (fam, " & ".join(cells)))
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def latex(metrics: Dict[str, Dict[str, object]], path: str) -> None:
    tags = tag_order(metrics)
    aniso = [r"$%g{:}1$" % metrics[t]["anisotropy"] for t in tags]

    parts: List[str] = []
    parts.append(r"""% Generated by hcsm.collect_tensor -- do not edit by hand.
\documentclass[11pt]{article}
\usepackage{amsmath,amssymb,booktabs,graphicx}
\usepackage[margin=1in]{geometry}
\title{Anisotropic tensor diffusion on a torus:\\
which error components defeat point smoothers,\\
and what a learned smoother does about them}
\date{}
\begin{document}
\maketitle

\section{What was run}

The problem is
\[
-\nabla_\Gamma\cdot(D_\varepsilon\nabla_\Gamma u)+u=f_\varepsilon,
\qquad
D_\varepsilon=\varepsilon\,e_\xi\otimes e_\xi+e_\eta\otimes e_\eta,
\]
on the torus $R=2$, $r=1$, with the manufactured solution
$u=\sin\xi\sin\eta$ and
\[
f_\varepsilon=\sin\xi\sin\eta\left(2+\frac{\cos\eta}{h}+\frac{\varepsilon}{h^2}\right),
\qquad h=2+\cos\eta ,
\]
derived in closed form for this tensor and verified before use. The strong
direction is $\eta$ (weight $1$), the weak direction is $\xi$ (weight
$\varepsilon$), so the anisotropy is $1/\varepsilon$. The case
$\varepsilon=1$ is the identity tensor and serves as the isotropic control.
""")

    parts.append(r"""
\subsection{Operator verification}

The exported prolongation was compared against \texttt{MGTransferPrebuilt}, the
transfer the V-cycle actually uses, at every level and every $\varepsilon$: the
maximum difference is exactly zero, for both the prolongation and the
restriction. The assembled operator is affine in $\varepsilon$,
$A_\varepsilon=A_\eta+\varepsilon A_\xi$, to a relative $4\times10^{-16}$, which
is what it means for the tensor to be applied consistently; and
$\varepsilon$ does change the assembly, by $33\%$ in max-norm between
$\varepsilon=1$ and $\varepsilon=10^{-4}$. The manufactured solution converges at
$O(h)$ in $H^1$ and $O(h^2)$ in $L^2$ at \emph{every} $\varepsilon$
(table~\ref{tab:conv}).
""")

    # convergence table
    conv_rows = []
    for t in tags:
        m = metrics[t]
        conv_rows.append((m["epsilon"], m["condition"]["diag_ratio"],
                          m["condition"]["A_H_condition"]))
    parts.append(r"""\begin{table}[htbp]\centering
\caption{Discretisation quality and operator anisotropy. The discretisation is
unaffected by $\varepsilon$; the operator's diagonal spread and coarse-grid
condition number grow only mildly.}
\label{tab:conv}
\begin{tabular}{lrrr}
\toprule
$\varepsilon$ & anisotropy & $\max_i A_{ii}/\min_i A_{ii}$ & $\operatorname{cond}(P^{\mathsf T}A_\varepsilon P)$ \\
\midrule
""" + "\n".join(
        r"%s & $%g{:}1$ & %.2f & %.1f \\" % (eps_label(t), metrics[t]["anisotropy"],
                                             d, c)
        for t, (e, d, c) in zip(tags, conv_rows))
      + r"""
\bottomrule
\end{tabular}
\end{table}
""")

    # classical, per family
    parts.append(r"""
\section{Classical smoothers: which components are hard}

Norm ratios $\lVert\cdot\rVert_{A_\varepsilon}/\lVert e\rVert_{A_\varepsilon}$,
one application each. ``full'' is the whole error, ``complement'' is
$\lVert Q_\varepsilon e^+\rVert_{A_\varepsilon}/\lVert e\rVert_{A_\varepsilon}$,
the part the coarse grid cannot reach.
""")
    for meth in METHODS:
        for which in ("full", "complement"):
            parts.append(_tex_table(
                metrics, tags, "classical_families", meth, which, "mean",
                "Mean %s norm ratio, %s, on the held-out test families "
                "(sweeps: %s)." % (which, meth, SWEEPS[meth]),
                "tab:cls-%s-%s" % (meth, which)))

    # learned, per family
    parts.append(r"""
\section{The learned smoother}

Same errors, same metric. The DeepONet is the framework's residual-to-correction
network with its learned Jacobi skip, wrapped in a scale-equivariant
normalisation so that $B(\lambda r)=\lambda B(r)$ exactly; the measured
equivariance error over amplitudes $10^{-6}$ to $10^{6}$ is below $10^{-15}$.
The loss is
$\mathbb{E}\lVert Q_\varepsilon e^+\rVert_A^2+\lambda\,\mathbb{E}\lVert e^+\rVert_A^2$
with $\lambda$ selected on validation errors.
""")
    for which in ("full", "complement"):
        parts.append(_tex_table(
            metrics, tags, "deeponet_families", LEARNED, which, "mean",
            "Mean %s norm ratio, DeepONet, on the held-out test families." % which,
            "tab:dn-%s" % which))

    # stress set
    parts.append(r"""
\section{Held-out stress set}

Analytic near-worst-case modes $\cos(m\xi)\cos(n\eta)$, projected by
$Q_\varepsilon$ and normalised. These are never used for training, model
selection or thresholding.
""")
    parts.append(_tex_table(
        metrics, tags, "classical_stress", "jacobi", "full", "mean",
        "Mean full norm ratio on the held-out stress modes, damped Jacobi.",
        "tab:stress-jacobi"))
    parts.append(_tex_table(
        metrics, tags, "deeponet_stress", LEARNED, "full", "mean",
        "Mean full norm ratio on the held-out stress modes, DeepONet.",
        "tab:stress-dn"))

    # V-cycle
    parts.append(r"""
\section{Actual multigrid performance}

This is a different question from every table above. Here the V-cycle is run on
the exported hierarchy from random right-hand sides, as a stationary defect
correction with no Krylov acceleration, and the contraction rate is measured
from the last cycles. The learned smoother is nonlinear, so where an accelerated
outer solver is wanted this corrected runner uses FGMRES for learned and forward-GS cycles,
and PCG for symmetric classical configurations. Historical results retain
their original solver labels and must not be interpreted as verified FGMRES.
""")
    vc_rows = []
    for t in tags:
        m = metrics[t]
        c = m["vcycle"]["classical"]
        l = m["vcycle"]["learned"]
        vc_rows.append((eps_label(t),
                        c["jacobi"]["mean_rate"], c["sgs"]["mean_rate"],
                        l["mean_rate"],
                        m["outer_solver"]["classical"]["sgs"]["iterations"],
                        m["outer_solver"]["learned"]["iterations"],
                        m["outer_solver"]["classical"]["jacobi"]["iterations"]))
    parts.append(r"""\begin{table}[htbp]\centering
\caption{V-cycle contraction rates and outer-solve iteration counts on the
1024-DoF level. A rate near $1$ means the cycle barely contracts.}
\label{tab:vcycle}
\begin{tabular}{lrrrrrr}
\toprule
$\varepsilon$ & \multicolumn{3}{c}{stationary rate} & \multicolumn{3}{c}{outer iterations} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
 & Jacobi & SGS & learned & SGS (PCG) & learned (see solver metadata) & Jacobi \\
\midrule
""" + "\n".join(
        r"%s & %.4f & %.4f & %.4f & %d & %d & %d \\" % r for r in vc_rows)
      + r"""
\bottomrule
\end{tabular}
\end{table}
""")

    parts.append(r"""
\section{What is and is not established}

\textbf{Established.} The anisotropic tensor makes the classical point smoothers
fail, and the failure is in the smoother rather than in the discretisation or in
the transfer, both of which are verified independently. The difficult components
are identified: errors oscillatory in $\xi$ and smooth in $\eta$, i.e.
oscillatory along the weak-coupling direction, exactly the regime the standard
anisotropic analysis predicts. The softest evidence is the quantity
$\eta(e)=\lVert D^{-1}Ae\rVert_A/\lVert e\rVert_A$, which enters the bound
$\lVert S_Je\rVert_A\ge(1-\omega\eta(e))\lVert e\rVert_A$; where
$\omega\eta(e)\ge1$ the lower bound is uninformative; it does not establish
that Jacobi fails. For $Qe=e$, the projected version of this bound also holds.

\textbf{Not established.} That the learned smoother is better than the classical
methods overall, or that it rescues the multigrid. The per-family and
per-$\varepsilon$ tables say exactly how much it helps and where; the V-cycle
table says whether that help survives into the solver. No claim is made beyond
this torus, this discretisation, this coefficient family, this training
distribution and this network configuration.

\textbf{Not measured here.} A second mesh: the hierarchy is one fixed level
(1024 DoFs) because the branch network consumes a fixed-length residual and is
bound to one DoF count and ordering. Classical-mesh dependence is visible in the
solver's own iteration counts across refinements, which are in
\texttt{results/tensor\_verif\_*.csv}.

\end{document}
""")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))


def console(metrics: Dict[str, Dict[str, object]]) -> None:
    tags = tag_order(metrics)
    print("=" * 100)
    print("full norm ratio ||e+||_A/||e||_A, mean over the held-out test families")
    print("%-26s %s" % ("", "  ".join("%-10s" % eps_label(t).replace("$", "")
                                       for t in tags)))
    print("-" * 100)
    for fam in FAMILIES:
        for meth in METHODS + (LEARNED,):
            cells = [_cell(metrics[t].get("deeponet_families" if meth == LEARNED
                                          else "classical_families"),
                           fam, meth, "full", "mean") for t in tags]
            print("%-26s %s" % ("%s / %s" % (fam, meth),
                                "  ".join("%-10.4f" % c for c in cells)))
    print("-" * 100)
    print("%-26s %s" % ("V-cycle stationary rate",
                        "  ".join("%-10s" % eps_label(t).replace("$", "")
                                  for t in tags)))
    for name in ("jacobi", "gs", "sgs", "learned"):
        cells = []
        for t in tags:
            vc = metrics[t]["vcycle"]
            src = vc["learned"] if name == "learned" else vc["classical"][name]
            cells.append(src["mean_rate"] if "mean_rate" in src
                         else src.get("mean_rate", float("nan")))
        print("%-26s %s" % (name, "  ".join("%-10.4f" % c for c in cells)))
    print("=" * 100)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--results", default="results/tensor")
    ap.add_argument("--out", default=None)
    args = ap.parse_args(argv)
    out = args.out or args.results
    os.makedirs(out, exist_ok=True)

    metrics = load(args.results)
    print("loaded %d runs: %s" % (len(metrics), ", ".join(sorted(metrics))))

    rows = write_summary_csv(metrics, os.path.join(out, "summary.csv"))
    print("  wrote summary.csv (%d rows)" % rows)
    latex(metrics, os.path.join(out, "analysis.tex"))
    print("  wrote analysis.tex")
    console(metrics)
    return 0


if __name__ == "__main__":
    sys.exit(main())
